### ISSUE TITLE
should resolve note1

### ISSUE THREAD

**Issue by pseudozach** [fiatjaf/nostr-gateway#12]
searching for `note13ze29u9dtxn4ua692fljfyyh4hdkvlcrdd2z04nl0ll48n0f0d4qpadtle` fails with 404. should be able to decode and then resolve the note.

**Comment by fiatjaf** [comment]
I agree.

**Comment by barkyq** [comment]
+1 was trying this today
also with `nevent1...` didn't work... thought it might by the phrasing of the prompt.

**Comment by fiatjaf** [comment]
It is not supported in the code. We must upgrade to the latest nostr-tools to get the NIP-19 handling functions, but that will require a little refactor.

**Comment by pseudozach** [comment]
I couldn't get around to this and I see this repo is updated and expects nip19 encoding now but now hex events are returning 500 error.
