### ISSUE TITLE
Link Hex Format of event key to their page

### ISSUE THREAD

**Issue by HamishMacEwan** [fiatjaf/nostr-gateway#16]
Loving the service!

Subject pretty much says it all.  

Getting from here: https://www.nostr.guru/p/3cc926bad81f4128b7c5d08e49a1025e0120d32b79285fd3f9b70fa2404992e5
to here: https://www.nostr.guru/e/f70188c506a9b37f5122c74c94ec6c1c25b97ca01dd029eb33d2988b42eb6be3

Shouldn't be a multi-click journey.

Props for the respect paid to, umm, ChatGPT what is the RFC that mentions be generous in what you accept and conservative in what you expect?

"The principle of "Be conservative in what you send, be liberal in what you accept" is often referred to as the Robustness Principle, also known as Postel's Law, named after Jon Postel, who wrote it in the context of TCP in 1981.

The statement can be found in Request for Comments (RFC) 793, which is the specification for the Transmission Control Protocol (TCP), in the section on "Robustness Principle". The principle was intended to guide the design of network protocols and was intended to encourage interoperability between different systems by suggesting that protocol implementations should be liberal in what they accept (i.e., they should accept a wide range of inputs) and conservative in what they send (i.e., they should limit their output to what is necessary and known to be correct)."

in that despite: "Paste a Nostr event key or a public key here in [NIP-19](https://github.com/nostr-protocol/nips/blob/master/19.md) format"

It silently accepts hex format keys too.

There are places for both liberal and conservative perspectives.

**Comment by fiatjaf** [comment]
I don't understand what you're suggesting.

**Comment by HamishMacEwan** [comment]
![image](https://user-images.githubusercontent.com/388061/219468556-c98edf7a-bfaf-47e8-a9fc-d363f9a7f305.png)
https://1drv.ms/u/s!Aorh3_-_gXYiouIGbIBcPlVc_rping

That number at the top should link to https://www.nostr.guru/e/d8ee0014e99033c3e14e2c2f58fd08b0b3ad388d6b32d325ca35c4dece9f261a

The remainder was praise for accepting both NIP-19 and Hex Format on the homepage.

**Comment by fiatjaf** [comment]
I see, thank you. I agree.

**Comment by gourcetools** [comment]
Done in https://github.com/fiatjaf/nostr-gateway/pull/23, i think you can close now @fiatjaf
