### ISSUE TITLE
Any plans to add open-source license

### ISSUE THREAD

**Issue by foxytanuki** [fiatjaf/nostr-gateway#17]
Thank you so much for creating an wonderful project.

Are there any plans to add an open-source license?

I really like the UI of [nostr.guru](https://www.nostr.guru/), but when Japanese is mixed in, it looks a little inconsistent and strange.
My first attempt to fix that was to add Japanese fonts to this repo, but it still looked strange.
Thus I would like to clone this repo and publish an alternative site on my domain with the entire font replaced and font size adjusted for Japanese users, is this possible?

#### Current
<img width="600" alt="Screenshot 2023-02-24 at 13 55 39" src="https://user-images.githubusercontent.com/45069709/221095488-f44c490b-b41a-4cfd-8876-8f2b0f226676.png">

#### Modified
<img width="600" alt="Screenshot 2023-02-24 at 14 42 16" src="https://user-images.githubusercontent.com/45069709/221101323-8d52045d-6367-4341-96c3-04f4e29c87b6.png">

**Comment by fiatjaf** [comment]
It's already open-source, please use and modify it. If you really need a license open a pull request with a license and I'll accept it.

**Comment by fiatjaf** [comment]
Thank you!
