### ISSUE TITLE
Design proposals

### ISSUE THREAD

**Issue by gourcetools** [fiatjaf/nostr-gateway#26]
**================================================================================================**
### Proposal 1 : Make boxes a little bit wider

**Reason: make box more compact and more readable.**

<img src="https://user-images.githubusercontent.com/120996278/222918697-5b83b0bb-658d-4ca2-906f-ac91b957ccb9.png" alt="image" width="400"> <- before
<br><br>
<img src="https://user-images.githubusercontent.com/120996278/222918787-7d25c3f8-82d2-47f5-bb79-85182efbebcc.png" alt="image" width="400"> <- after
<br><br>
**================================================================================================**
### Proposal 2 : NIP button that goes to NIP specifications for the event kind:
**Reason: make it easy to see and browse wich event kind is associated with wich NIP specifications . I'm not sure how to handle multple nips. The idea is that link for kind 3 goes to nip-03.md, simply.**

Before:

<img src="https://user-images.githubusercontent.com/120996278/222919232-70eadc9a-70b1-49d4-b0f1-e1726687a5b3.png" alt="image" width="400"> <- before
<br><br>
<img src="https://user-images.githubusercontent.com/120996278/222919237-ffb11758-7c5e-4fd1-ad73-e1f9b06c5026.png" alt="image" width="400"><- after
<br><br>
**================================================================================================**
### Proposal 3: Align stuff, capitalize
**Reason: More readable feelsgoodman**

Before -> After:

<img src="https://user-images.githubusercontent.com/120996278/222875628-dec93dda-4167-4e09-96e4-a4c34b894a61.png" alt="image" width="100"> <img src="https://user-images.githubusercontent.com/120996278/222875613-c172bd90-336f-4e98-8248-657401dbed09.png" alt="image" width="100">
<br><br>
**================================================================================================**
### Proposal 4:  Put event kind number in a box
**Reason: Feelsgoodman**

<img src="https://user-images.githubusercontent.com/120996278/222919909-76dad294-3818-4745-b494-083f4fd7bb01.png" alt="image" width="400"><- before
<br><br>
<img src="https://user-images.githubusercontent.com/120996278/222919918-72f945e4-a71f-4fe1-af01-80825890ed1c.png" alt="image" width="400"><- after
**================================================================================================**

**Comment by fiatjaf** [comment]
Except for the NIP button I think I am fine with all these. The NIP button would work if there was a straightforward way to map the event kind to the NIP, but there is not.

**Comment by gourcetools** [comment]
https://github.com/fiatjaf/nostr-gateway/pull/27
